version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge