version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    expose:
      - 5000
    volumes:
      - ./app:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web