name: drawing-chat
services:
  - name: web
    git:
      branch: main
      repo_clone_url: ${https://github.com/orozcoc78/draw_and_talk}
    build_command: pip install -r requirements.txt
    run_command: gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:8080 app:app
    envs:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    instance_size_slug: basic-xxs
    http_port: 8080
    cors:
      allow_origins:
        - "*"
    health_check:
      http_path: /
    routes:
      - path: /
      - path: /ws
        preserve_path_prefix: true